### ISSUE TITLE
setCircleColor(R.color.xxx)无效

### ISSUE THREAD

**Issue by LittleWaver** [backkomyoung/CircleView#1]
##使用环境
CircleView被用于RecyclerView的item布局中，结构如下：
···
	<LinearLayout
		xxx>
		<LinearLayout
			xxx>
			<me.songning.library.CircleView
				android:id="@+id/iv_type"
				android:layout_width="50dp"
				android:layout_height="50dp"
				android:layout_gravity="center_vertical"
				app:textSize="15sp"
				app:textColor="@color/white"/>
			...
		</LinearLayout>
	</LinearLayout>
···
在RecyclerView的adapter中设置每个item中元素的值：
···
    @Override
    public void onBindViewHolder(MyHolderView holder, int position) {
        switch (xxx) {//holder.type为RecyclerView.ViewHolder中所对应上面布局iv_type的CircleView实例
            case "xxx":
                holder.type.setCircleColor(R.color.room);
                holder.type.setText("xxx");
                break;
            case "xxx":
                holder.type.setCircleColor(R.color.dining);
                holder.type.setText("xxx");
                break;
            case "xxx":
                holder.type.setCircleColor(R.color.send);
                holder.type.setText("xxx");
                break;
        }
		...
    }
···
##出现的问题
在RecyclerView的adapter中根据不同的条件设置每一个item中CircleView的颜色为相对应颜色setCircleColor(R.color.xxx)时，结果是
在界面中呈现的item中CirclerView的颜色不为相对应的颜色，似乎是存在颜色值的覆盖或者丢失现象。
##问题的解决
在RecyclerView的adapter中设置每个item中元素的值的代码改为：
···
    public void onBindViewHolder(MyHolderView holder, int position) {
        switch (xxx) {//holder.type为RecyclerView.ViewHolder中所对应上面布局iv_type的CircleView实例
            case "xxx":
                holder.type.setCircleColor(Color.parseColor("#CC6600"));
                holder.type.setText("xxx");
                break;
            case "xxx":
                holder.type.setCircleColor(Color.parseColor("#006600"));
                holder.type.setText("xxx");
                break;
            case "xxx":
                holder.type.setCircleColor(Color.parseColor("#663399"));
                holder.type.setText("xxx");
                break;
        }
		...
    }
···
后，在界面中呈现的item中CircleView的颜色则呈现出来的为代码中设置的相对应颜色。
##以上现象的原因
请问，以上出现的问题和问题的解决是什么原因或者什么原理?

**Comment by backkomyoung** [comment]
很久以前的库，刚刚重新看了下代码。可能的原因：
1.发现Circle.setCircleViewColor方法里面直接调用的是Paint.setColor方法，看到了@ColorInt注解了颜色参数，该方法最好接收的是十六进制颜色代码，不知道直接传@ColorRes类型的会不会有问题。
2.ViewHolder复用导致数据错乱。
3.我里面那个全局参数mCircleColor参数在RecyclerView可能会出问题。就一个类，你可以copy修改试试^ ^

**Comment by LittleWaver** [comment]
谢谢指点啦！！！
