### ISSUE TITLE
Could not find library

### ISSUE THREAD

**Issue by chitgoks** [backkomyoung/CircleView#2]
Could not find me.songning.CircleView:library:1.0.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/me/songning/CircleView/library/1.0.0/library-1.0.0.pom
       - https://repo.maven.apache.org/maven2/me/songning/CircleView/library/1.0.0/library-1.0.0.pom
       - https://jitpack.io/me/songning/CircleView/library/1.0.0/library-1.0.0.pom
     Required by:
         project :app

I use 
google()
mavenCentral()

in buildscript.repositories and allprojects.repositories 

Thoughts?

**Comment by chitgoks** [comment]
this works ok if jcenter() is added. but since it will be deprecated ...

**Comment by finalrose7** [comment]
> this works ok if jcenter() is added. but since it will be deprecated ...

I will be migrating it to MavenCentral soon.

**Comment by finalrose7** [comment]
Now migrated to mavenCentral , please read the README.
